# Site settings
title:          TELKblog
description:    "Test blog"
baseurl:        "/"
url:            "https://weblog.telk.kr"

# Google Analytics
google_analytics: UAâ€”XXXXXXXX-X

timezone: Asia/Seoul

# Author
author:
  name:         TELK
  url:          https://telk.kr
  email:        telk5093@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Defaults
defualts:
  -
    scopes:
      path: ""
    values:
      layout: post
      author: TELK

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

remote_theme: chesterhow/tale

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  #- jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale