# Site settings
title:          TELKblog
description:    "TELK의 블로그"
host:           localhost
port:           4000
baseurl:        ""
url:            "https://blog.telk.kr"

# Google Analytics
google_analytics:    UA-199820069-1
google_analytics_v4: G-ESB087YT8T

timezone: Asia/Seoul

# Author
author:
  name:         TELK
  url:          https://telk.kr
  email:        telk5093@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Defaults
defaults:
  -
    scopes:
      path: ""
    values:
      layout: post
      author: TELK

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

remote_theme: chesterhow/tale

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  #- jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         telk5093